export const DELETE_ITEM = "DELETE_ITEM"
export const UPDATE_ITEM = "UPDATE_ITEM"
export const ADD_ITEM = "ADD_ITEM"
export const SET_ITEM = "SET_ITEM"
export const ARCHIVE_ITEM = "ARCHIVE_ITEM"
export const DELETE_ALL = "DELETE_ALL"
export const SHOW_ARCHIVED = "SHOW_ARCHIVED"
